// Traducciones para emails de reportes de pago
export interface EmailTranslations {
  subject: string;
  header: {
    title: string;
    subtitle: string;
  };
  greeting: string;
  content: {
    attachmentMessage: string;
    periodText: string;
    questionContact: string;
    closing: string;
    totalLoads: string;
    grossEarnings: string;
    totalExpenses: string;
    netPayment: string;
    attachmentNote: string;
    automaticEmail: string;
  };
}

export const emailTranslations: Record<string, EmailTranslations> = {
  en: {
    subject: "Payment Report - {driverName} - {period}",
    header: {
      title: "FleetNest TMS",
      subtitle: "Driver Payment Report"
    },
    greeting: "Dear {driverName},",
    content: {
      attachmentMessage: "Please find attached your detailed payment report for the period from {startDate} to {endDate}.",
      periodText: "from {startDate} to {endDate}",
      questionContact: "If you have any questions about this report, please don't hesitate to contact us.",
      closing: "Best regards,",
      totalLoads: "Total Loads:",
      grossEarnings: "Gross Earnings:",
      totalExpenses: "Total Expenses:",
      netPayment: "NET PAYMENT:",
      attachmentNote: "📎 The detailed PDF report is attached to this email with complete information on loads, expenses and deductions.",
      automaticEmail: "This is an automatic email generated by FleetNest TMS"
    }
  },
  es: {
    subject: "Reporte de Pago - {driverName} - {period}",
    header: {
      title: "FleetNest TMS",
      subtitle: "Reporte de Pago del Conductor"
    },
    greeting: "Estimado {driverName},",
    content: {
      attachmentMessage: "Adjunto encontrará su reporte de pago detallado para el período del {startDate} al {endDate}.",
      periodText: "del {startDate} al {endDate}",
      questionContact: "Si tiene alguna pregunta sobre este reporte, no dude en contactarnos.",
      closing: "Cordialmente,",
      totalLoads: "Total de Cargas:",
      grossEarnings: "Ingresos Brutos:",
      totalExpenses: "Total Gastos:",
      netPayment: "PAGO NETO:",
      attachmentNote: "📎 El reporte detallado en PDF está adjunto a este correo con información completa de cargas, gastos y deducciones.",
      automaticEmail: "Este es un correo automático generado por FleetNest TMS"
    }
  }
};

export function getEmailTranslations(language: string = 'en'): EmailTranslations {
  return emailTranslations[language] || emailTranslations.en;
}

export function interpolateText(template: string, variables: Record<string, string>): string {
  return template.replace(/\{(\w+)\}/g, (match, key) => variables[key] || match);
}