project_id = "htaotttcnjxqzpsrqwll"

[functions.send-payment-report]
verify_jwt = false

[functions.geotab-sync]
verify_jwt = false

[functions.setup-superadmin]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.fmcsa-lookup]
verify_jwt = false

[functions.accept-google-invitation]
verify_jwt = false

[functions.validate-invitation]
verify_jwt = false

[functions.activate-driver-account]
verify_jwt = false

[functions.analyze-pdf]
verify_jwt = false