project_id = "htaotttcnjxqzpsrqwll"

[functions.geotab-sync]
verify_jwt = false

[functions.setup-superadmin]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.fmcsa-lookup]
verify_jwt = false

[functions.accept-google-invitation]
verify_jwt = false